SS-2: create filters on restaurants page
SaraSpahic/ABH-DevDays-JavaProject pull request #2
Opened 2018-03-22 14:58 UTC by SaraSpahic

- Price filter: Completed
- Rating filter: Problems with pagination
- Cuisine filter: Problems with request string

2018-03-22 15:01 UTC, SaraSpahic commented on app/services/RestaurantService.java
> +    @SuppressWarnings("unchecked")
I accidentally reformatted the code so now it looks that whole file is changed, but my actual changes are only in method findRestaurantsWithFilter().

2018-03-26 20:34 UTC, irfankrijestorac requested changes

2018-03-26 20:34 UTC, irfankrijestorac commented on app/controllers/RestaurantController.java
> +						.setCuisineFilter(request().getQueryString(CUISINE_FILTER))
Here you should use `String[] cuisineFilter = request().queryString().get(CUISINE_FILTER);` to get list of all cousines not only first one.

2018-03-26 20:34 UTC, irfankrijestorac commented on app/models/helpers/RestaurantFilter.java
> +    public String cuisine;
Now we have a list here, not only one String

2018-03-26 20:46 UTC, irfankrijestorac requested changes

2018-03-26 20:46 UTC, irfankrijestorac commented on app/services/RestaurantService.java
> +        if (restaurantFilter.rating != null && restaurantFilter.rating != 0) {
How about get all reviews that meet filter conditions, and from reviews list get list of restaurant ids that should be returned?

2018-04-10 09:37 UTC, merged