SS-6: Create activity logs
SaraSpahic/ABH-DevDays-JavaProject pull request #4
Opened 2018-04-18 22:31 UTC by SaraSpahic

2018-04-18 22:32 UTC, SaraSpahic commented
![](https://github.trello.services/images/mini-trello-icon.png) [SS-6: Create activity logs](https://trello.com/c/eEqCvyFd/7-ss-6-create-activity-logs)

2018-04-19 22:15 UTC, irfankrijestorac requested changes

2018-04-19 22:15 UTC, irfankrijestorac commented on conf/evolutions/default/1.sql
> +CREATE TABLE IF NOT EXISTS activity_log (
You need to add new SQL statement to new file (3.sql). CREATE TABLE command would never be executed because step (1) is already completed.

2018-04-19 22:15 UTC, irfankrijestorac commented on app/services/UserService.java
> +            logActivity(ActivityType.USER_REGISTER, "New user has registered for the website.");
You should move all messages to constants

2018-04-26 06:27 UTC, merged